# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jan Wedekind
tagline:          'Computer Scientist (PhD)'
description:      'Machine vision, robotics, software engineering.'
url:              http://www.wedesoft.de
baseurl:          /

author:
  name:           'Jan Wedekind'
  url:            https://twitter.com/wedesoft

paginate:         5

# Custom vars
github:
  repo:           https://github.com/wedesoft/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-youtube
  - jekyll-vimeo
